spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
  redis:
    url: ${REDIS_URL}
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/prod

logging:
  level:
    root: WARN
    com.ecom: INFO

auth:
  jwt:
    secret: ${JWT_SECRET}
