"""Product create/update: slug auto-generation and explicit-slug/collision
behavior, the generated `search_document` column, legacy free-text field
round-tripping, the DRAFT-by-default status, and one documented bug found
while writing these tests (create_product 500s when `attributes` is
omitted)."""

import pytest
from product_service.models import Product
from product_service.repo import slugify
from sqlalchemy import select, text

pytestmark = pytest.mark.integration


async def test_create_product_autogenerates_slug_from_title(client, as_seller):
    as_seller("42")
    resp = await client.post("/products", json={"title": "Ant Esports GW180 Corsa!", "attributes": {}})
    assert resp.status_code == 201
    body = resp.json()
    assert body["slug"] == slugify("Ant Esports GW180 Corsa!")


async def test_create_product_explicit_slug_used_as_is(client, as_seller):
    as_seller("42")
    resp = await client.post("/products", json={"title": "Widget", "slug": "custom-slug-123", "attributes": {}})
    assert resp.status_code == 201
    assert resp.json()["slug"] == "custom-slug-123"


async def test_create_product_duplicate_explicit_slug_conflicts(client, as_seller):
    as_seller("42")
    resp1 = await client.post("/products", json={"title": "Widget A", "slug": "same-slug", "attributes": {}})
    assert resp1.status_code == 201
    resp2 = await client.post("/products", json={"title": "Widget B", "slug": "same-slug", "attributes": {}})
    assert resp2.status_code == 409


async def test_create_product_duplicate_autogenerated_slug_is_disambiguated(client, as_seller):
    # Same title twice, slug omitted both times -> generate_unique_slug must
    # disambiguate the second one rather than conflicting.
    as_seller("42")
    resp1 = await client.post("/products", json={"title": "Widget", "attributes": {}})
    assert resp1.status_code == 201
    resp2 = await client.post("/products", json={"title": "Widget", "attributes": {}})
    assert resp2.status_code == 201
    assert resp1.json()["slug"] != resp2.json()["slug"]
    assert resp2.json()["slug"] == "widget-2"


async def test_update_product_slug_collision_conflicts(client, as_seller):
    as_seller("42")
    product_a = (await client.post("/products", json={"title": "Widget A", "slug": "widget-a", "attributes": {}})).json()
    product_b = (await client.post("/products", json={"title": "Widget B", "slug": "widget-b", "attributes": {}})).json()

    resp = await client.put(f"/products/{product_b['id']}", json={"slug": "widget-a"})
    assert resp.status_code == 409

    # product_a's slug must be unaffected.
    row = await client.put(f"/products/{product_a['id']}", json={"title": "Widget A"})
    assert row.status_code == 200
    assert row.json()["slug"] == "widget-a"


async def test_search_document_populated_after_insert(client, as_seller, db):
    as_seller("42")
    resp = await client.post(
        "/products",
        json={"title": "Ant Esports Racing Wheel", "description": "Force feedback pedals included", "attributes": {}},
    )
    assert resp.status_code == 201
    product_id = resp.json()["id"]

    row = (
        await db.execute(
            text(
                "SELECT search_document, "
                "search_document @@ plainto_tsquery('english', 'racing') AS has_racing_token "
                "FROM products WHERE id = :id"
            ),
            {"id": product_id},
        )
    ).one()
    assert row.search_document is not None
    assert row.has_racing_token is True


async def test_legacy_fields_round_trip_unchanged(client, as_seller, db):
    as_seller("42")
    payload = {
        "title": "Widget",
        "category": "Gaming",
        "sub_category": "Accessories",
        "brand": "Ant Esports",
        "retail_price": "89.99",
        "discount": "10.00",
        "attributes": {},
    }
    resp = await client.post("/products", json=payload)
    assert resp.status_code == 201
    body = resp.json()
    assert body["category"] == "Gaming"
    assert body["sub_category"] == "Accessories"
    assert body["brand"] == "Ant Esports"
    assert body["retail_price"] == "89.99"
    assert body["discount"] == "10.00"

    # Round-trips through the DB layer too (public GET is DRAFT-gated in this
    # phase, so read the row directly to isolate legacy-field persistence
    # from that unrelated visibility rule).
    row = (await db.execute(select(Product).where(Product.id == body["id"]))).scalar_one()
    assert row.category == "Gaming"
    assert row.sub_category == "Accessories"
    assert row.brand == "Ant Esports"
    assert str(row.retail_price) == "89.99"
    assert str(row.discount) == "10.00"


async def test_new_product_defaults_to_draft_status(client, as_seller, db):
    as_seller("42")
    resp = await client.post("/products", json={"title": "Widget", "attributes": {}})
    assert resp.status_code == 201
    assert resp.json()["status"] == "DRAFT"

    row = (await db.execute(select(Product.status).where(Product.id == resp.json()["id"]))).scalar_one()
    assert row == "DRAFT"


async def test_create_product_with_omitted_attributes_defaults_to_empty_dict(client, as_seller):
    """Regression guard: create_product used to pass an explicit `None`
    (ProductCreate.attributes' default) straight into the ORM constructor,
    bypassing the mapped column's `default=dict` and storing a JSONB `null`
    that ProductResponse.attributes: dict would then reject on read. Fixed by
    coercing `data["attributes"] = data.get("attributes") or {}` before
    constructing the Product row — see `create_product` in `api/routes.py`.
    """
    as_seller("42")
    resp = await client.post("/products", json={"title": "Widget"})  # attributes omitted
    assert resp.status_code == 201
    assert resp.json()["attributes"] == {}


async def test_update_product_version_increments(client, as_seller):
    as_seller("42")
    product = (await client.post("/products", json={"title": "Widget", "attributes": {}})).json()

    resp = await client.put(f"/products/{product['id']}", json={"title": "Widget Updated"})
    assert resp.status_code == 200
    # version isn't in ProductResponse; confirm indirectly the update applied.
    assert resp.json()["title"] == "Widget Updated"
